spring.application.name=user-service
spring.datasource.url=jdbc:mysql://localhost:3306/eventdb
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
//Output:
//get api json output:
//http://localhost:8080/users
//to get registeration output:
//mvn spring-boot:run
//http://localhost:8080
// database output:
//Steps:
//mysql -u root -p
//USE eventdb;
//SELECT * FROM users;
//Exit;

